### ISSUE TITLE
How to convert between scan modes

### ISSUE THREAD

**Issue by crazyfree** [weacast/weacast-grib2json#12]
Hi, 
I have trouble with grib2 scan mode. 
My model expects scan mode 0 but data is in mode 64.

If you don't want to introduce new feature. Kindly advices how to reach it.

Thanks!

**Comment by claustres** [comment]
Hi, sorry for the delay but I was on leave.

Could you please share more context about what you are trying to achieve and possibly a sample file ? For instance are you only using this tool to get data in json or do you also use weacast to manage your data ?

I might be wrong but the scanning mode simply tells you how to interpret the data correctly for your use case and this should not really change something in the reader, it simply reads data and give them you back.

**Comment by claustres** [comment]
Closing now as no feedback, please reopen if required.
