### ISSUE TITLE
grib2json command arguments for 850 mb level U/V compoents

### ISSUE THREAD

**Issue by bryanray67** [weacast/weacast-grib2json#2]
Hello, I'm trying to find the correct command arguments for grib2json.  I see the example for 10 meters above ground, but I'm wanting the 850 mb level.

The --fv code should be 850 (just a guess)?
the --fs code should be 100 instead of 103 (just a guess)?

My command is:
grib2json --names --data --fp 2 --fs 100 --fv 850 --ouput testgrib.json gribfile.grib
I do not get any errors, but the resulting json file is empty.

Any suggestions?
Many thanks!
Bryan

**Comment by claustres** [comment]
You can use panoply https://www.giss.nasa.gov/tools/panoply/ to check your grib file for the right values.

I also often use the grib filter interface http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p50.pl to only download the right variable then extract it simply with -d and -o arguments.

**Comment by bryanray67** [comment]
Thank you for your reply.  I am currently only downloading the single variable at a time, so using -d and -o should do the trick if I leave off --fs and --fv?

**Comment by claustres** [comment]
Yes it works for me

**Comment by claustres** [comment]
Does it work for you ?

**Comment by bryanray67** [comment]
Hello.  Yes, it did work for me.  Thank you very much.
